### ISSUE TITLE
"rna.run_kallisto": "false"

### ISSUE THREAD

**Issue by summer-lemon** [ENCODE-DCC/rna-seq-pipeline#66]
I set the "rna.run_kallisto": "false" parameter, but the error is reported as follows:
Required workflow input 'rna.kallisto_index' not specified
Required workflow input 'rna.kallisto_ramGB' not specified
Required workflow input 'rna.kallisto_number_of_threads' not specified

**Comment by ottojolanki** [comment]
`run_kallisto` is Boolean, I think we should define it without quotes (i.e. just `false` instead of `"false"`) to be interpreted correctly.

**Comment by summer-lemon** [comment]
Thank you for your reply, I tried using false instead of "false", but the same error was reported.

**Comment by ottojolanki** [comment]
Could you post the full `input.json` so I can investigate further?

**Comment by summer-lemon** [comment]
My input.json is as follows:
{
    "rna.run_kallisto" : false,
    "rna.endedness" : "single",
    "rna.fastqs_R1" : [["./rep1_ENCSR510QZW_chr19only_10000_reads.fastq.gz"],["./rep2_ENCSR510QZW_chr19only_10000_reads.fastq.gz"]],
    "rna.bamroot" : "SE_unstranded",
    "rna.align_index" : "./GRCh38_v24_ERCC_phiX_starIndex_chr19only.tgz",
    "rna.rsem_index" : "./GRCh38_v24_ERCC_phiX_rsemIndex_chr19only.tgz",
    "rna.strandedness" : "unstranded",
    "rna.strandedness_direction" : "unstranded",
    "rna.chrom_sizes" : "./test_data/GRCh38_EBV.chrom.sizes",
    "rna.rna_qc_tr_id_to_gene_type_tsv" : "./gencodeV24pri-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv",
    "rna.align_ncpus" : 15,
    "rna.align_ramGB" : 60,
    "rna.rsem_ncpus" : 15,
    "rna.rsem_ramGB" : 60,
    "rna.bam_to_signals_ncpus" : 15,
    "rna.bam_to_signals_ramGB" : 30

}
Thank you very much!

**Comment by ottojolanki** [comment]
I am debugging this now. I think you may be running old version of the code, because in the newest version `rna.kallisto_index`, `rna.kallisto_ramGB` and `rna.kallisto_number_of_threads` as you can see in https://github.com/ENCODE-DCC/rna-seq-pipeline/blob/master/rna-seq-pipeline.wdl#L39. I will let you know soon if I can reproduce the problem.

**Comment by summer-lemon** [comment]
OK, thank you very much!

**Comment by ottojolanki** [comment]
Ok, I had a successful run with the following input:
```
{
  "rna.run_kallisto": false,
  "rna.align_disk": "local-disk 20 HDD",
  "rna.align_index": "test_data/GRCh38_v24_ERCC_phiX_starIndex_chr19only.tgz",
  "rna.align_ncpus": 2,
  "rna.align_ramGB": 4,
  "rna.bam_to_signals_disk": "local-disk 20 HDD",
  "rna.bam_to_signals_ncpus": 1,
  "rna.bam_to_signals_ramGB": 2,
  "rna.bamroot": "SE_unstranded",
  "rna.chrom_sizes": "test_data/GRCh38_EBV.chrom.sizes",
  "rna.endedness": "single",
  "rna.fastqs_R1": [
    [
      "test_data/rep1_ENCSR510QZW_chr19only_10000_reads.fastq.gz"
    ],
    [
      "test_data/rep2_ENCSR510QZW_chr19only_10000_reads.fastq.gz"
    ]
  ],
  "rna.mad_qc_disk": "local-disk 20 HDD",
  "rna.rna_qc_disk": "local-disk 20 HDD",
  "rna.rna_qc_tr_id_to_gene_type_tsv": "transcript_id_to_gene_type_mappings/gencodeV24pri-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv",
  "rna.rsem_disk": "local-disk 20 HDD",
  "rna.rsem_index": "test_data/GRCh38_v24_ERCC_phiX_rsemIndex_chr19only.tgz",
  "rna.rsem_ncpus": 2,
  "rna.rsem_ramGB": 4,
  "rna.strandedness": "unstranded",
  "rna.strandedness_direction": "unstranded"
}
```

Let's figure out what the problem is. First let's make sure you are running the most recent version. Please pull the most recent version in by doing `git pull origin master` in the pipeline folder (or by just recloning the whole repo). 
I did my successful run using the most recent version of caper, `1.2.1` that you can install with command `pip install caper`. I was running it with python `3.7.4` in a fresh virtual environment. I ran caper with default versions of `womtool` and `cromwell` (no configuration required). The full run command was:
`caper run rna-seq-pipeline.wdl -i SE_testing_without_kallisto_input.json -m test_SE_without_kallisto_meta.json --docker`
I am running `Docker version 19.03.8, build afacb8b` on mac. I think the most important thing is to first make sure the pipeline code you are running is up to date. Let me know how it works out.

**Comment by summer-lemon** [comment]
Thank you, I will try the latest version of the pipeline.

**Comment by summer-lemon** [comment]
I use the latest version, set the "rna.run_kallisto": "false" parameter, and it ran successfully.
I have another question I want to ask you. If use this pipeline to analyze species other than humans and mice, I did not use the merge_anno.wdl method to build the index, but directly use star and rsem to build the index, and then compress it into gtz format, and then provide it to this pipeline, it can also run, will there be a problem?

**Comment by ottojolanki** [comment]
Great to hear you got the pipeline running! You should be able to run like that. Merge anno is basically just making an additional piece of annotation `gtf` file from spikeins and tRNAs and concatenating that with the gencode annotation, so if all you want to use is the reference genome, then you should be fine doing what you are doing.

**Comment by summer-lemon** [comment]
Ok, than you very much!
