### ISSUE TITLE
rna.align error when attempting to run pipeline on test data

### ISSUE THREAD

**Issue by gilesc** [ENCODE-DCC/rna-seq-pipeline#74]
I'm trying to successfully run the tests on local docker. This is the script I'm using:

```
#!/usr/bin/env bash

basedir=$(mktemp -d) 
echo "Running in $basedir"
trap "rm -rf $basedir" EXIT
pip install --user caper 1> /dev/null 2>/dev/null

cd $basedir
git clone https://github.com/ENCODE-DCC/rna-seq-pipeline.git
cd rna-seq-pipeline

curl https://storage.googleapis.com/circle_ci_test_data/rna-seq-pipeline/GRCh38_v24_ERCC_phiX_starIndex_chr19only.tgz -o test_data/GRCh38_v24_ERCC_phiX_starIndex_chr19only.tgz
curl https://storage.googleapis.com/circle_ci_test_data/rna-seq-pipeline/Homo_sapiens.GRCh38.cdna.all.chr19_ERCC_phix_k31_kallisto.idx -o test_data/Homo_sapiens.GRCh38.cdna.all.chr19_ERCC_phix_k31_kallisto.idx

cat <<EOF > input.json
{
    "rna.endedness" : "single",
    "rna.fastqs_R1" : [["${basedir}/rna-seq-pipeline/test_data/rep1_ENCSR510QZW_chr19only_10000_reads.fastq.gz"],["${basedir}/rna-seq-pipeline/test_data/rep2_ENCSR510QZW_chr19only_10000_reads.fastq.gz"]],
    "rna.bamroot" : "SE_unstranded",
    "rna.align_index" : "${basedir}/rna-seq-pipeline/test_data/GRCh38_v24_ERCC_phiX_starIndex_chr19only.tgz",
    "rna.rsem_index" : "${basedir}/rna-seq-pipeline/test_data/GRCh38_v24_ERCC_phiX_rsemIndex_chr19only.tgz",
    "rna.kallisto_index" : "${basedir}/rna-seq-pipeline/test_data/Homo_sapiens.GRCh38.cdna.all.chr19_ERCC_phix_k31_kallisto.idx",
    "rna.strandedness" : "unstranded",
    "rna.strandedness_direction" : "unstranded",
    "rna.chrom_sizes" : "${basedir}/rna-seq-pipeline/test_data/GRCh38_EBV.chrom.sizes",
    "rna.align_ncpus" : 2,
    "rna.align_ramGB" : 4,
    "rna.rsem_ncpus" : 2,
    "rna.rsem_ramGB" : 4,
    "rna.kallisto_number_of_threads" : 2,
    "rna.kallisto_ramGB" : 4,
    "rna.kallisto_fragment_length" : [250, 250],
    "rna.kallisto_sd_of_fragment_length" : [10, 10],
    "rna.rna_qc_tr_id_to_gene_type_tsv" : "${basedir}/rna-seq-pipeline/transcript_id_to_gene_type_mappings/gencodeV24pri-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv",
    "rna.bam_to_signals_ncpus" : 1,
    "rna.bam_to_signals_ramGB" : 2,
    "rna.align_disk" : "local-disk 20 HDD",
    "rna.kallisto_disk" : "local-disk 20 HDD",
    "rna.rna_qc_disk" : "local-disk 20 HDD",
    "rna.bam_to_signals_disk" : "local-disk 20 HDD",
    "rna.mad_qc_disk" : "local-disk 20 HDD",
    "rna.rsem_disk" : "local-disk 20 HDD"

}
EOF

caper run rna-seq-pipeline.wdl -i input.json -m testrun_metadata.json --docker

```

As far as I understand, it's identical to the tutorial, with two exceptions. I've replaced "[PATH_TO_REPO]" and "\<path-to-repo\>" (it's inconsistent) with "${basedir}". Secondly, I've duplicated "250" and "10" to "rna.kallisto_fragment_length" and "rna.kallisto_sd_of_fragment_length" in the array, as unless I do this, I get an error that seems to be an off-by-one.

After doing this, I get the following error:

```
"causedBy": [
            {
                "causedBy": [],
                "message": "Job rna.align:0:2 exited with return code -1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."
            }
        ],
        "message": "Workflow failed"
```

I don't imagine my kallisto version matters, as I think this should be running in docker. I'm on Arch Linux. I'm fairly stumped.

```
$ kallisto version
kallisto, version 0.46.1

$ caper --version
1.4.1

$ python --version
3.8.6

$ java -version
openjdk version "1.8.0_265"

$ docker --version
Docker version 19.03.13-ce, build 4484c46d9d
```

**Comment by ottojolanki** [comment]
First of all, thanks for catching the mistake in the example input considering the kallisto fragment length and SD. I will fix that. I'll try to run your script on my machine to see if I can duplicate the problem. My kneejerk reaction is that the the problem might be caused by using `mktemp`, but we'll see.

**Comment by ottojolanki** [comment]
Unfortunately I am unable to reproduce the problem. Everything works perfectly for me (probably not what you wanted to hear..). 
I am running on mac, but the environment should be very similar on the important bits:
```
01:04:20 in ~/Documents/Testing_things/rna_seq_issue74 via issue74
$ python --version
Python 3.8.5

01:05:42 in ~/Documents/Testing_things/rna_seq_issue74
$ docker --version
Docker version 19.03.13, build 4484c46d9d

01:05:53 in ~/Documents/Testing_things/rna_seq_issue74 via issue74
$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)

This caper version seems to be using `Cromwell` version 52.
```
Also I modified the script on line 6 to install the same version of caper into my virtual env:
`pip install caper==1.4.1`

Due to everything running fine for me, I cannot debug this with the information available. 
I have some ideas though. Aligner failing quietly without specific error might suggest some resource based problem.
One thing I would check how many resources your docker engine is allowed to use (for me it is 8cpus, 8GB RAM, 1GB swap), it may default to something too small.
Another would (quite obviously, I know) to make sure your machine is not running out of resources. 
If your docker resources and actual bare metal resources seem sufficient and run is still failing, I think next step would be to run this in a non-temporary directory so we could have a look at the outputs and try to figure it out.

**Comment by gilesc** [comment]
Thanks. I'm 99% sure mktemp isn't the problem, as I first encountered this problem before using tempdirs, and got the same errors. I only added that to have a self-contained script to post here.

I doubt system resources are the problem, I've got 100+GB RAM free, and plenty of disk space.

WRT docker, I'm less sure. I have a default install. On Arch Linux as best I can tell, container resources aren't limited. The systemd file contains:

```
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
```
But I'm far from a docker expert. Or do you instead mean changing the parameters like ```rna.align_RAMGB```? Will that propagate to Docker? I tried upping them to 16 with no luck.

In case you want to pursue this further, I ran all this and compressed everything into a tarball:

https://www.dropbox.com/s/rgju426v7dokji2/issue73.tgz?dl=0

Another data point is that I tried on a different machine. Also Arch, but even more RAM, disk, etc, and somewhat different versions of the underlying software, for example JDK10. I'm going to try one of our Ubuntu machines next.

**Comment by ottojolanki** [comment]
It is good to know that the system resources definitely are not the problem here. I mean changing the Docker engine preferences (This limits how much resources it is allowed to consume. I am do not know how these are set on Arch Linux, but as always the documentation is your friend.) I can confirm that `mktemp` is not the problem. Keep me posted on how it works with more docker resources and/or on Ubuntu.
