### ISSUE TITLE
Errors with dependent software

### ISSUE THREAD

**Issue by rameshvnair** [ENCODE-DCC/rna-seq-pipeline#80]
`FileNotFoundError: [Errno 2] No such file or directory: 'kallisto'`

I tried adding all dependent tools like STAR, kallisto, RSEM, etc to the PATH but that doesn't work either. Aren't the dependencies with the accepted versions already in the singularity container? 

I ran thus:
`caper run $PIPELINE_WDL_PATH/rna-seq-pipeline.wdl -i PE_stranded.json`

Rather than repeatedly download the pipeline and run within the folder as shown in the HOWTO I'm pointing to the WDL using an environment variable and adding the python scripts in src to the PATH. I tried adding the `--singularity` flag to run using singularity on the Stanford SCG cluster but that failed. Is the recommendation then to always download the pipeline for every run and run within the folder?

If I want to create my own STAR and RSEM indexes do I run thus?
`caper run make_index_wdl/build_genome_index.wdl`

**Comment by rameshvnair** [comment]
I was able to resolve the missing dependencies by providing these at runtime. So the questions that remain are the following.

If I want to create my own STAR and RSEM indexes do I run thus?
caper run make_index_wdl/build_genome_index.wdl

I notice that the pipeline also runs kallisto. Currently, it's unclear whether RSEM is using STAR or kallisto mapping? How do I run just the STAR-RSEM pipeline without kallisto? Is there a setting for this in "caper run"?

**Comment by rameshvnair** [comment]
> `FileNotFoundError: [Errno 2] No such file or directory: 'kallisto'`
> 
> I tried adding all dependent tools like STAR, kallisto, RSEM, etc to the PATH but that doesn't work either. Aren't the dependencies with the accepted versions already in the singularity container?
> 
> I ran thus:
> `caper run $PIPELINE_WDL_PATH/rna-seq-pipeline.wdl -i PE_stranded.json`
> 
> Rather than repeatedly download the pipeline and run within the folder as shown in the HOWTO I'm pointing to the WDL using an environment variable and adding the python scripts in src to the PATH. I tried adding the `--singularity` flag to run using singularity on the Stanford SCG cluster but that failed. Is the recommendation then to always download the pipeline for every run and run within the folder?
> 
> If I want to create my own STAR and RSEM indexes do I run thus?
> `caper run make_index_wdl/build_genome_index.wdl`

I was able to resolve the missing dependencies by providing these at runtime. So the questions that remain are the following.

If I want to create my own STAR and RSEM indexes do I run thus? Any guidance here is welcome.
`caper run make_index_wdl/build_genome_index.wdl`

I notice that the pipeline also runs kallisto. Currently, it's unclear whether RSEM is using STAR or kallisto mapping? How do I run just the STAR-RSEM pipeline without kallisto? Is there a setting for this in `caper run`?

**Comment by ottojolanki** [comment]
Hello, @rameshvnair and sorry for very delayed answer. For the first problem, it seems that you should add `--docker` into the run command to have the pipeline run in the docker container that contains all the dependencies. 
You can omit running kallisto by setting `run_kallisto` input parameter to `false` (see https://github.com/ENCODE-DCC/rna-seq-pipeline/blob/master/docs/reference.md for input descriptions). RSEM uses STAR mapping, kallisto part is an independent addon. 
Index building is a bit fiddly due to ENCODE using multiple files as inputs (the main reference, tRNAs and spikeins). The description of the inputs and general process can be found in https://github.com/ENCODE-DCC/rna-seq-pipeline/blob/master/docs/reference.md#note-about-resources but if you let me know what your inputs are I can also help with it. I promise to answer faster this time..
